name: slsa

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  PRODUCT_VERSION: 0.4.12
  APP_NAME: demo_product
  VALINT_BOM_AUTHOR_NAME: Jane Doe
  VALINT_BOM_AUTHOR_EMAIL: gc@scribesecurity.com
  VALINT_BOM_AUTHOR_PHONE: 052-9000000
  VALINT_BOM_SUPPLIER_NAME: Scribe-Security
  VALINT_BOM_SUPPLIER_URL: www.scribesecurity.com
  VALINT_BOM_SUPPLIER_EMAIL: info@scribesecurity.com
  VALINT_BOM_SUPPLIER_PHONE: 001-001-0011
  GITHUB_RUN_NUM: ${{ github.run_number }}
  DOCKER_CONFIG: $HOME/.docker

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
      with:
        egress-policy: audit

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

        
    - name: Login to Docker Hub
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
      with:
        registry: docker.io
        username: pranaycshah
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build the Docker image
      run: docker build . -t pranaycshah/todolist-demo:${{ github.sha }}
      
#    - name: Push the Docker image
#      run: docker push pranaycshah/todolist-demo:${{ github.sha }}


    - name: Generate SLSA provenance
      id: valint_json
      uses: scribe-security/action-slsa@d83bb63c91c85a5dc3584a6fec3d13fd739fbd80 # master
      with:
        target: 'pranaycshah/node-vuln:latest'
        scribe-enable: true
        scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
        format: statement
        output-file: my_slsa.json
        product-version: $${{ env.PRODUCT_VERSION }}

    - name: Upload SLSA provenance as artifact
      uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
      with:
        name: scribe-slsa
        path: my_slsa.json

    - name: Upload evidence as artifact
      uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
      with:
        name: scribe-evidence
        path: scribe/
